broker = "124.221.89.92:1883"
user = "admin"
passwd = "admin"
postgres = "host=124.221.89.92 port=5432 user=farmer password=mysecretpassword dbname=farm-iot sslmode=disable"
grpcAddr = "127.0.0.1:7891"

[influxdb]
url = "http://124.221.89.92:8086"
auth = "DLGOlxx9qW4858WBxyIqLAXJ_FPOzersD20zk8eZOZuX__anUkk25tZbLvXIxTyZKjD_R8t1Yu4CEPIvz7hXOw=="

