broker = "127.0.0.1:1883"
user = "admin"
passwd = "admin"
postgres = "host=127.0.0.1 port=5432 user=farmer password=mysecretpassword dbname=farm-iot sslmode=disable"

[influxdb]
url = "http://127.0.0.1:8086"
auth = "exAmple-t0ken-958a-f490-c7fd0eda5e9e"
