// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/MoefulYe/farm-iot/database/postgres/ent/balance"
	"github.com/MoefulYe/farm-iot/database/postgres/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	balanceFields := schema.Balance{}.Fields()
	_ = balanceFields
	// balanceDescWhen is the schema descriptor for when field.
	balanceDescWhen := balanceFields[0].Descriptor()
	// balance.DefaultWhen holds the default value on creation for the when field.
	balance.DefaultWhen = balanceDescWhen.Default.(func() time.Time)
}
