basePath: /api
definitions:
  models.DeviceInfo:
    properties:
      born_at:
        type: string
      dead_at:
        type: string
      id:
        type: string
      reason:
        type: string
    type: object
  models.KeepAlive:
    properties:
      health:
        type: number
      id:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      time:
        type: string
      weight:
        type: number
    type: object
  models.LoginReq:
    properties:
      passwd:
        type: string
      username:
        type: string
    type: object
  models.Msg:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  models.Paged-models_DeviceInfo:
    properties:
      cnt:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.DeviceInfo'
        type: array
    type: object
  models.RegisterReq:
    properties:
      passwd:
        type: string
      username:
        type: string
    type: object
  models.Resp-Paged[models_DeviceInfo]:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/models.Paged-models_DeviceInfo'
      msg:
        type: string
    type: object
  models.Resp-array_models_DeviceInfo:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.DeviceInfo'
        type: array
      msg:
        type: string
    type: object
  models.Resp-array_models_KeepAlive:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.KeepAlive'
        type: array
      msg:
        type: string
    type: object
  models.Resp-models_DeviceInfo:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/models.DeviceInfo'
      msg:
        type: string
    type: object
  models.Resp-models_Token:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/models.Token'
      msg:
        type: string
    type: object
  models.Token:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /cow:
    get:
      consumes:
      - application/json
      parameters:
      - description: jwt
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        maximum: 40
        minimum: 0
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-Paged[models_DeviceInfo]'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      security:
      - ApiKeyAuth: []
      summary: get all info
      tags:
      - getInfo
  /cow/{uuid}:
    get:
      consumes:
      - application/json
      parameters:
      - description: jwt
        in: header
        name: Authorization
        required: true
        type: string
      - description: uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-models_DeviceInfo'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      security:
      - ApiKeyAuth: []
      summary: get uuid info by uuid
      tags:
      - getInfo
  /cow/keep-alive:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: fields
        type: string
      - in: query
        name: start
        type: string
      - in: query
        name: stop
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-array_models_KeepAlive'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      security:
      - ApiKeyAuth: []
      summary: keepalive
      tags:
      - keep-alive
  /cow/keep-alive/{uuid}:
    get:
      consumes:
      - application/json
      parameters:
      - description: jwt
        in: header
        name: Authorization
        required: true
        type: string
      - description: uuid
        in: path
        name: uuid
        required: true
        type: string
      - in: query
        name: fields
        type: string
      - in: query
        name: start
        type: string
      - in: query
        name: stop
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-array_models_DeviceInfo'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      security:
      - ApiKeyAuth: []
      summary: keepalive by uuid
      tags:
      - keep-alive
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号和密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-models_Token'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      tags:
      - login
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名和密码
        in: body
        name: body-params
        required: true
        schema:
          $ref: '#/definitions/models.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/models.Resp-models_Token'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/models.Msg'
      tags:
      - register
swagger: "2.0"
