// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: die.proto

package die

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason    string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Uuid      string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_die_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_die_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_die_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Record) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Record) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DieMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *DieMsg) Reset() {
	*x = DieMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_die_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DieMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DieMsg) ProtoMessage() {}

func (x *DieMsg) ProtoReflect() protoreflect.Message {
	mi := &file_die_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DieMsg.ProtoReflect.Descriptor instead.
func (*DieMsg) Descriptor() ([]byte, []int) {
	return file_die_proto_rawDescGZIP(), []int{1}
}

func (x *DieMsg) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type KillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *KillReq) Reset() {
	*x = KillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_die_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillReq) ProtoMessage() {}

func (x *KillReq) ProtoReflect() protoreflect.Message {
	mi := &file_die_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillReq.ProtoReflect.Descriptor instead.
func (*KillReq) Descriptor() ([]byte, []int) {
	return file_die_proto_rawDescGZIP(), []int{2}
}

func (x *KillReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_die_proto protoreflect.FileDescriptor

var file_die_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x61, 0x72,
	0x6d, 0x2e, 0x63, 0x6f, 0x77, 0x22, 0x52, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x06, 0x44, 0x69, 0x65,
	0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x72, 0x6d, 0x2e, 0x63, 0x6f, 0x77, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x1d, 0x0a,
	0x07, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x0a, 0x5a, 0x08,
	0x66, 0x61, 0x72, 0x6d, 0x2f, 0x64, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_die_proto_rawDescOnce sync.Once
	file_die_proto_rawDescData = file_die_proto_rawDesc
)

func file_die_proto_rawDescGZIP() []byte {
	file_die_proto_rawDescOnce.Do(func() {
		file_die_proto_rawDescData = protoimpl.X.CompressGZIP(file_die_proto_rawDescData)
	})
	return file_die_proto_rawDescData
}

var file_die_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_die_proto_goTypes = []interface{}{
	(*Record)(nil),  // 0: farm.cow.Record
	(*DieMsg)(nil),  // 1: farm.cow.DieMsg
	(*KillReq)(nil), // 2: farm.cow.KillReq
}
var file_die_proto_depIdxs = []int32{
	0, // 0: farm.cow.DieMsg.record:type_name -> farm.cow.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_die_proto_init() }
func file_die_proto_init() {
	if File_die_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_die_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_die_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DieMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_die_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_die_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_die_proto_goTypes,
		DependencyIndexes: file_die_proto_depIdxs,
		MessageInfos:      file_die_proto_msgTypes,
	}.Build()
	File_die_proto = out.File
	file_die_proto_rawDesc = nil
	file_die_proto_goTypes = nil
	file_die_proto_depIdxs = nil
}
